name: locked
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      run: docker-compose up -d
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
      with:
        version: 1.0.10
    - name: Use Python Dependency and Poetry Virtualenv Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-pip-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Bootstrap
      run: |
        poetry run bootstrap --ci
        poetry install --no-root --extras sip2
        poetry run pip install --upgrade pip
        poetry run pip install --upgrade coveralls
    - name: Run Test
      run: |
        poetry run run-tests
    - name: Upload Coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: test
      run: poetry run coveralls
